import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Ceramic",
  description: "Generated by yGa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* HEADER */}
        <header className="sticky top-0 z-50 bg-white/90 backdrop-blur border-b border-gray-100">
          <div className="max-w-7xl mx-auto flex items-center justify-between px-4 py-2">
            <div className="flex items-center gap-2">
              <img src="/logo.png" alt="Logo" className="h-10 w-auto" />
            </div>
            <nav>
              <ul className="flex gap-8 font-semibold text-[#1C4880] text-lg">
                <li><a href="#" className="hover:text-[#269FD0] transition">Inicio</a></li>
                <li><a href="#quienes-somos" className="hover:text-[#269FD0] transition">Quiénes somos</a></li>
                <li><a href="#contacto" className="hover:text-[#269FD0] transition">Contacto</a></li>
              </ul>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
